from enum import Enum, auto

class ReportingState(Enum):
  PRE_REPORTING = 'PRE_REPORTING'
  DESIGNATED_REPORTING = 'DESIGNATED_REPORTING'
  OPEN_REPORTING = 'OPEN_REPORTING'
  CROWDSOURCING_DISPUTE = 'CROWDSOURCING_DISPUTE'
  AWAITING_NEXT_WINDOW = 'AWAITING_NEXT_WINDOW'
  AWAITING_FINALIZATION = 'AWAITING_FINALIZATION'
  FINALIZED = 'FINALIZED'
  FORKING = 'FORKING'
  AWAITING_NO_REPORT_MIGRATION = 'AWAITING_NO_REPORT_MIGRATION'
  AWAITING_FORK_MIGRATION = 'AWAITING_FORK_MIGRATION'
